"""Public contracts for authoritative ETH credit-spread strategy math."""

from eth_credit_hedge.domain.strategy_math.contracts import (
    CoverageResult,
    DeltaStepSpacingConfig,
    EntryPercentStopConfig,
    EqualOptionLossSpacingConfig,
    LevelCountSpacingConfig,
    LevelMath,
    LevelSpacingMode,
    OptionSpreadState,
    OptionValuationContext,
    OptionValuationMode,
    PriceStepFractionStopConfig,
    PriceStepSpacingConfig,
    QuantityRoundingMode,
    SpacingConfig,
    StopConfig,
    StopMode,
    require_valuation_context,
    validate_spacing_configuration_fields,
)
from eth_credit_hedge.domain.strategy_math.errors import (
    DeltaSpacingUnavailableError,
    InvalidConfigurationError,
    InvalidUnitsError,
    NonPositiveNetProfitError,
    QuantizationCoverageError,
    StrategyMathError,
    UnsupportedValuationError,
)
from eth_credit_hedge.domain.strategy_math.units import (
    DeltaExposure,
    Money,
    Price,
    Quantity,
    Rate,
    Seconds,
    Volatility,
)

__all__ = [
    "CoverageResult",
    "DeltaExposure",
    "DeltaSpacingUnavailableError",
    "DeltaStepSpacingConfig",
    "EntryPercentStopConfig",
    "EqualOptionLossSpacingConfig",
    "InvalidConfigurationError",
    "InvalidUnitsError",
    "LevelCountSpacingConfig",
    "LevelMath",
    "LevelSpacingMode",
    "Money",
    "NonPositiveNetProfitError",
    "OptionSpreadState",
    "OptionValuationContext",
    "OptionValuationMode",
    "Price",
    "PriceStepFractionStopConfig",
    "PriceStepSpacingConfig",
    "Quantity",
    "QuantityRoundingMode",
    "QuantizationCoverageError",
    "Rate",
    "Seconds",
    "SpacingConfig",
    "StopConfig",
    "StopMode",
    "StrategyMathError",
    "UnsupportedValuationError",
    "Volatility",
    "require_valuation_context",
    "validate_spacing_configuration_fields",
]
