"""Public contracts for authoritative ETH credit-spread strategy math."""

from eth_credit_hedge.domain.strategy_math.contracts import (
    CoverageResult,
    DeltaStepSpacingConfig,
    EntryPercentStopConfig,
    EqualOptionLossSpacingConfig,
    LevelCountSpacingConfig,
    LevelMath,
    LevelSpacingMode,
    OptionLegValuationParameters,
    OptionSpreadState,
    OptionValuationContext,
    OptionValuationMode,
    PriceStepFractionStopConfig,
    PriceStepSpacingConfig,
    QuantityRoundingMode,
    SpacingConfig,
    StopConfig,
    StopMode,
    parse_spacing_configuration,
    parse_stop_configuration,
    require_valuation_context,
    validate_spacing_configuration_fields,
    validate_stop_configuration_fields,
)
from eth_credit_hedge.domain.strategy_math.errors import (
    DeltaSpacingUnavailableError,
    InvalidConfigurationError,
    InvalidUnitsError,
    NonMonotonicSpacingError,
    NonPositiveNetProfitError,
    QuantizationCoverageError,
    RootNotBracketedError,
    StrategyMathError,
    UnsupportedValuationError,
)
from eth_credit_hedge.domain.strategy_math.costs import (
    CostBreakdown,
    ExecutionCostContext,
    calculate_cost_breakdown,
)
from eth_credit_hedge.domain.strategy_math.quantization import (
    InstrumentRules,
    quantize_quantity,
)
from eth_credit_hedge.domain.strategy_math.recovery import (
    ActualStopDebt,
    calculate_actual_stop_debt,
)
from eth_credit_hedge.domain.strategy_math.sizing import (
    SizingResult,
    SizingStatus,
    net_profit_and_loss_per_unit,
    size_hedge,
    zero_cost_directional_profit_and_loss_per_unit,
)
from eth_credit_hedge.domain.strategy_math.units import (
    DeltaExposure,
    Money,
    Price,
    Quantity,
    Rate,
    Seconds,
    Volatility,
)
from eth_credit_hedge.domain.strategy_math.spacing import (
    LevelSpacingEngine,
    SpacingLevel,
    solve_monotonic_price,
)
from eth_credit_hedge.domain.strategy_math.stops import (
    StopGeometryEngine,
    StrategyMathEngine,
)
from eth_credit_hedge.domain.strategy_math.valuation import (
    ExpirationOptionValuation,
    OptionValuationPort,
)

__all__ = [
    "ActualStopDebt",
    "CostBreakdown",
    "CoverageResult",
    "DeltaExposure",
    "DeltaSpacingUnavailableError",
    "DeltaStepSpacingConfig",
    "EntryPercentStopConfig",
    "ExecutionCostContext",
    "EqualOptionLossSpacingConfig",
    "InvalidConfigurationError",
    "InvalidUnitsError",
    "InstrumentRules",
    "LevelCountSpacingConfig",
    "LevelMath",
    "LevelSpacingMode",
    "LevelSpacingEngine",
    "Money",
    "NonPositiveNetProfitError",
    "NonMonotonicSpacingError",
    "OptionLegValuationParameters",
    "OptionSpreadState",
    "OptionValuationContext",
    "OptionValuationMode",
    "Price",
    "PriceStepFractionStopConfig",
    "PriceStepSpacingConfig",
    "Quantity",
    "QuantityRoundingMode",
    "QuantizationCoverageError",
    "Rate",
    "RootNotBracketedError",
    "Seconds",
    "SpacingConfig",
    "SpacingLevel",
    "SizingResult",
    "SizingStatus",
    "StopConfig",
    "StopGeometryEngine",
    "StopMode",
    "StrategyMathEngine",
    "StrategyMathError",
    "UnsupportedValuationError",
    "Volatility",
    "ExpirationOptionValuation",
    "OptionValuationPort",
    "parse_spacing_configuration",
    "parse_stop_configuration",
    "require_valuation_context",
    "solve_monotonic_price",
    "calculate_actual_stop_debt",
    "calculate_cost_breakdown",
    "quantize_quantity",
    "net_profit_and_loss_per_unit",
    "size_hedge",
    "zero_cost_directional_profit_and_loss_per_unit",
    "validate_spacing_configuration_fields",
    "validate_stop_configuration_fields",
]
